### ISSUE TITLE
Can't install via Berkshelf

### ISSUE THREAD

**Issue by noradaiko** [poise/poise-python#1]
I got an error as following:

```
$ berks install
Resolving cookbook dependencies...
Fetching 'poise-python' from git@github.com:poise/poise-python.git (at master)
The resource at '/tmp/d20150813-27271-14qi8s8' does not appear to be a valid cookbook. Does it have a metadata.rb?
```

This `application_python` cookbook example is using this cookbook:
https://github.com/poise/application_python/blob/master/test/cookbooks/application_python_test/recipes/django.rb

How can I use it?

**Comment by coderanger** [comment]
See https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook for info on using a pre-release version of this cookbook.

**Comment by noradaiko** [comment]
Thanks!
