### ISSUE TITLE
Python 2.7 not available in machine that has Python 2.6.6

### ISSUE THREAD

**Issue by roberto-mardeni** [poise/poise-python#100]
After installing in Centos 6.7 using:

```ruby
python_runtime '2.7' do
  options :system
end
```

and checking the chef client logs applied it successfully:

```bash
  * python_runtime[2.7] action install
    * poise_languages_scl[python27] action install
      * execute[subscription-manager repos --enable rhel-server-rhscl-6-rpms] action run
        - execute subscription-manager repos --enable rhel-server-rhscl-6-rpms
      * ruby_block[flush_yum_cache] action run
        - execute the ruby block flush_yum_cache
      * yum_package[python27] action install
        - install version 1.1-25.el6 of package python27
      * yum_package[python27-python-devel] action install (up to date)

    * python_runtime_pip[2.7] action install (up to date)
    * python_package[setuptools] action install (up to date)
    * python_package[wheel] action install (up to date)
    * python_package[virtualenv] action install (up to date)
     (up to date)
```

python2.7 is not available and pip is not available, what am I missing?

**Comment by coderanger** [comment]
I think you meant `provider :system` :) With what you have it is installing via SCL packages so you have to `scl enable` to see them.

**Comment by coderanger** [comment]
(notably there is no system package for 2.7 on EL6 by default so unless you made your own, that will fail)

**Comment by roberto-mardeni** [comment]
Excuse my ignorance, but can you be a little bit more explicit, what do I need to do to get installed and enabled in the same resource call?

Also, that options parameter is like that in the readme file of your repo, so I guess you should update that.

**Comment by coderanger** [comment]
`options :system` is how you set per-provider options for that specific provider, but it doesn't actually set the provider. To do that use the `provider` property. You can have options set for multiple providers (or even all providers) for cases where you want to customize the default provider behaviors.
