### ISSUE TITLE
breaks with pip10

### ISSUE THREAD

**Issue by yonilevy** [poise/poise-python#109]
In addition to the [regex issue](https://github.com/poise/poise-python/issues/107)

There's also these imports that no longer work with pip10:
https://github.com/poise/poise-python/blob/df4685bff206868d2d0c9582a667d35828149537/lib/poise_python/resources/python_package.rb#L47

Apparently these are internal APIs that shouldn't have been used, and now they're gone altogether (actually, moved inside _internal, but definitely can't rely on that).
Here's the announcement: https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html

Any plans to make this work with pip10?

Thanks!

**Comment by IanAtkin** [comment]
Yes. Just discovered this little problem. Bizarre message reads...
```
STDERR: The python_package resource requires pip >= 6.1.0, currently 10.0.0
```
That was definitely a double-take for me.

**Comment by coderanger** [comment]
There's like 10 tickets open for this, please stop with the metoos.

**Comment by dknell** [comment]
@coderanger how about closing the dupes with a HELPFUL message or a link to the fix, since apparently EVERYONE is having this issue.

**Comment by dragon788** [comment]
If you unpin and upgrade to 1.7.0 the issue is resolved.
