### ISSUE TITLE
System pip packages

### ISSUE THREAD

**Issue by ronlipke** [poise/poise-python#11]
Is there any way to install packages with pip for system python other than having to specify the path?  I have `virutalenv_version` set to false, and the only declared `python_runtime` is using the :system option, but all pip packages are installed with the `opt/rh/python27` binary.

**Comment by coderanger** [comment]
Can you paste the code you are using? If it looks like:

```ruby
python_runtime '2' do
  provider :system
end
```

that should force it to use system packages even on RHEL distros.

**Comment by ronlipke** [comment]
@coderanger Thanks! This worked perfect on Centos 7.  

I didn't see any mention of the `provider` method in the readme, and using `:system` is only mentioned in the 'Provider Options" section.  Would it help to clarify this?

**Comment by coderanger** [comment]
It isn't something specific to this cookbook, that's how you set the provider for any Chef resource. The docs for each provider also show an example.

**Comment by ronlipke** [comment]
:facepalm:

Completely missed that.  Thanks again.
