### ISSUE TITLE
Please release the version with 18.04 support!

### ISSUE THREAD

**Issue by dennybaa** [poise/poise-python#117]

**Comment by dennybaa** [comment]
@coderanger 
PS.
It makes sense to get rid of the `halite_gem` approach completely and make a "normal" cookbook :)
Lately always something breaks in poise python, first pip 10 with hardcoded regexp now bionic.
The way the cookbook is made is **ultra wrong**, while people could just fork and contribute to the cookbook they have to wait until you update the gem or do "fuckery" as you'd say.

**Comment by coderanger** [comment]
I'll release it when I get time. Anyone can fork/contribute to this cookbook if they want, and instructions on using a pre-release version are available at https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook.

Closing this as both inflammatory and non-actionable.

**Comment by dennybaa** [comment]
@coderanger well it what it is, thanks for the docs :) My point is the whole halite approach brings nothing to users from the perspective of friendliness. And from the perspective of code re-usability it also jet-legged, I really doubt there's a wide audience which gonna use chef provider gem :)
Wrapping one package into another package and versioning both. And also berks extension... Sounds heavy.

**Comment by coderanger** [comment]
Halite isn't for users, it's a development and management tool and I've written many words about why it is superior to plain cookbooks for the types of things I write. Feel free to look them up.
