### ISSUE TITLE
Gives an: No metadata file found for python error, when trying add this through Vagrant's Cheffile

### ISSUE THREAD

**Issue by hayetech** [poise/poise-python#119]
Hi,

Upon trying to install this cookbook directly through 
`'python', :git => 'https://github.com/poise/poise-python.git'` in Cheffile

It gives the following error, whenever I try to `vagrant up`,

`No metadata file found for python from https://github.com/poise/poise-python.git#master! If this should be a cookbook, you might consider contributing a metadata file upstream or forking the cookbook to add your own metadata file. (Librarian::Error)`

I'm trying to setup django environment in ubuntu through vagrant and virtual box
([following this tutorial](https://github.com/tsavecodes/djawesome)).

Note: The above linked tutorial follows [this](https://github.com/poise/python) deprecated version of python cookbook and upon viewing [this stackflow answer](https://stackoverflow.com/questions/44482351/error-undefined-method-python-for-chefnodeattribute0x00000003f78ef8), I just changed the URL for python in the cheffile of this tutorial.

Am I doing this right or is there another way to alter the deprecated python cookbook?
@coderanger

**Comment by coderanger** [comment]
So my cookbooks aren't usable directly for a variety of complex reasons. The way you use them is from the Chef Supermarket. You can pull from git, but you need a special Berkshelf plugin and there is no equivalent for Librarian.

Related: Librarian is super duper dead and you should very not be using it. At a minimum use Berkshelf, but probably look at using Policyfiles :)

**Comment by merteroglu01** [comment]
How can we solve this problem ?

**Comment by hayetech** [comment]
By reconfiguring your vagrantfile to use berkshelf and in the process inflicting the required changes in the cheffile, if needed.
