### ISSUE TITLE
FrozenError - can't modify frozen Array - container.rb

### ISSUE THREAD

**Issue by pazmarianoj** [poise/poise-python#128]
Version #: 1.7.0

Recipe Compile Error in /var/chef/cache/cookbooks/poise-python/libraries/default.rb

FrozenError

can't modify frozen Array

Cookbook Trace:

  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:in `included'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:in `include'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:in `poise_subresource_container'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:in `block in Poise'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `include'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `<class:Resource>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `<module:PythonRuntime>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `<module:Resources>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `<module:PoisePython>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources.rb:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/cheftie.rb:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-python/libraries/default.rb:in `<top (required)>'
Relevant File Content:
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:
```ruby
                @container_default
              end 
            end 
            def included(klass)
              super
              klass.extend(ClassMethods)
220 >>        klass.const_get(:HIDDEN_IVARS) << :@subcontexts
              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
            end 
          end 
          extend ClassMethods
        end 
      end 
    end 
  end
```

**Comment by coderanger** [comment]
Dup of #124 and fixed already.
