### ISSUE TITLE
scl provider on RHEL inconsistencies

### ISSUE THREAD

**Issue by jfbibeau** [poise/poise-python#13]
Hi there,

So I'm having some real problems getting a consistent python 2.7 install on RHEL 6.6. 

This is how I'm installing it in my recipe:
```
python_runtime 'vagrant' do
  provider :scl
  version '2.7'
end
```
Most of the time it fails with this error during provisioning (I'm using the cookbook with vagrant+chef):
```
==> vagrant-slave-2: Mixlib::ShellOut::ShellCommandFailed
==> vagrant-slave-2: ------------------------------------
==> vagrant-slave-2: rpm_package[rhscl-python27] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 112) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> vagrant-slave-2: 
==> vagrant-slave-2: ---- Begin output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
==> vagrant-slave-2: 
==> vagrant-slave-2: ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm ----
==> vagrant-slave-2: 
==> vagrant-slave-2: STDOUT: 
==> vagrant-slave-2: 
==> vagrant-slave-2: STDERR: curl: (7) couldn't connect to host
==> vagrant-slave-2: 
==> vagrant-slave-2: error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm failed: No such file or directory
==> vagrant-slave-2: 
==> vagrant-slave-2: ---- End output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
==> vagrant-slave-2: 
==> vagrant-slave-2: ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm ----
==> vagrant-slave-2: 
==> vagrant-slave-2: Ran rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
==> vagrant-slave-2: 
==> vagrant-slave-2: ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm returned 1
```

I'm not sure exactly what it's doing here? It looks like it's running an rpm command which results in a curl call? And this curl call is failing (Trying it manually results in an empty file?).

However if I run the exact same chef cookbook again a 2nd time, it goes through fine and seems to install python from the repository:

```
==> vagrant-slave-2: [2015-11-13T12:57:32-05:00] INFO: rpm_package[rhscl-python27] installed rhscl-python27 at 1-2
==> vagrant-slave-2: [2015-11-13T12:57:32-05:00] INFO: ruby_block[flush_yum_cache] called
==> vagrant-slave-2: [2015-11-13T12:57:35-05:00] INFO: yum_package[python27] installing python27-1.1-17.el6 from rhscl-python27-epel-6-x86_64 repository
==> vagrant-slave-2: [2015-11-13T12:58:31-05:00] INFO: yum_package[python27] installed python27 at 1.1-17.el6
```

I've been trying to troubleshoot the first failure and I have no idea what's causing it, or why the 2nd run would work fine. Any ideas?

Thanks!

**Comment by jfbibeau** [comment]
Ok I think I'm seeing the issue... I'm using a proxy on my end. It looks like whatever shell is spun off to run the following command is not taking into account proxy variables?
```
rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm
```

Is it possible the shell that is used to run this doesn't properly inherit OS environment variables? If I unset https_proxy I can reproduce the same error.
```
$ unset https_proxy
$ rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm
curl: (7) couldn't connect to host
error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/epel-6-x86_64/download/rhscl-python27-epel-6-x86_64.noarch.rpm failed: No such file or directory
```

I'm guessing this isn't actually needed and the 2nd run keeps going past it and completes successfully?

**Comment by coderanger** [comment]
Guessing between the first and second rounds something gets written out that makes RPM work with the proxy? Can you try setting `ENV['https_proxy'] = 'whatever'` in the code before you hit the python install?

**Comment by jfbibeau** [comment]
Yeah that could be it - proxy gets loaded via a file provisioned in /etc/profile.d/, maybe it doesn't get sourced until the 2nd time around. Didn't get to the bottom of it as I needed to build from source so I'm back to the origin python cookbook. Thanks for the quick reply.
