### ISSUE TITLE
What does this cookbook do?

### ISSUE THREAD

**Issue by onknows** [poise/poise-python#132]
I was considering using this cookbook to install Python. But this made me realize there is probably more to it than I thought. 

My thought was that `python` should be a command and not a command not found. To achieve this I applied poise-python cookbook and found that `python` was still not a command.

What does this cookbook do? It installs a Python runtime environment but what i a python runtime environment actually? How is it different from `python` command?  

When I apt-get python on Ubuntu it gives me a python command. What can I do with a python runtime created with poise-python?

**Comment by coderanger** [comment]
There is no difference, but there are more ways than `apt-get install python` to install Python. For example, you might want to install from a different package, or use the portable-pypy tarballs, or install on a platform that doesn't use `apt`. The `python_runtime` resource abstracts the install process for all of those different options.
