### ISSUE TITLE
centos6 default python binary not properly setting LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jslusher** [poise/poise-python#16]
This is after a default install of a python virtualenv using the python_runtime and python_virtualenv resources from this cookbook.

    [root@server ]# source venv/bin/activate
    (venv)[root@server ]# python 
    python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No     such file or directory
    (venv)[root@server ]# which python
    /opt/venv/bin/python
    (venv)[root@server ]# updatedb
    (venv)[root@server ]# locate libpython2.7.so.1.0
    /opt/rh/python27/root/usr/lib64/libpython2.7.so.1.0
    (venv)[root@server ]# export LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
    (venv)[root@server ]# python
    Python 2.7.8 (default, Jun  9 2015, 19:27:51)
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> quit()

**Comment by coderanger** [comment]
When using it interactively, you need to either manage that stuff yourself or use the `scl enable` tool. This is a structural problem with the SCL binaries because they don't (yet?) set an rpath internally. /cc @ncoghlan
