### ISSUE TITLE
All the SoftwareCollections URLs have broke

### ISSUE THREAD

**Issue by mattse** [poise/poise-python#19]
poise-python is no longer able to install versions of python for CentOS 7, and probably many others.  The error traces back to a 404 with the SoftwareCollections URL.  

Here's some relevant error text:
```
146.148.49.248         Mixlib::ShellOut::ShellCommandFailed
146.148.49.248         ------------------------------------
146.148.49.248         Expected process to exit with [0], but received '1'
146.148.49.248         ---- Begin output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
146.148.49.248         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ----
146.148.49.248         STDOUT:
146.148.49.248         STDERR: curl: (22) The requested URL returned error: 404 Not Found
146.148.49.248         error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm failed: No such file or directory
146.148.49.248         ---- End output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
146.148.49.248         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm ----
146.148.49.248         Ran rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
146.148.49.248         ' https://www.softwarecollections.org/en/scls/rhscl/python27/epel-7-x86_64/download/rhscl-python27-epel-7-x86_64.noarch.rpm returned 1
```

Visiting that URL indeed shows a missing file.  It seems that the URL format has changed to https://www.softwarecollections.org/repos/rhscl/rh-python34/rhscl-rh-python34-el7-epel-7-x86_64/noarch/rhscl-rh-python34-epel-7-x86_64-1-2.noarch.rpm  

This change happened at 2015-12-04 12:13.  Maybe it would be best to not rely on these hard coded URLs  by softwarecollections so a breaking change doesn't break this cookbook in the future.

**Comment by coderanger** [comment]
The SCLs site is currently having an outage. It crashed entirely a few days ago, and now the data seems to have been moved. I'm working with the SCL admins, so far I am proceeding under the assumption that the file move as in error.

**Comment by mattse** [comment]
Thanks for the quick update @coderanger !

**Comment by coderanger** [comment]
I'm *::jazzhands::* unthrilled with SCL as an upstream but I don't have a ton of choice right now. The SCL server seems to be one VPS box with only two or three people poking stuff relatively directly by hand. Some folks are working on getting a more "real" setup for the packages now that it has a logistical home. /cc @ncoghlan

**Comment by mattse** [comment]
Yes, this is quite a pain.  At the moment, we cannot use Chef to provision any Production servers that use Poise-Python.  We may have to reevaluate how we manage/install Python on our servers for more reliability.  What's the reason for not relying on the OS package manager (yum for CentOS) to install python?

**Comment by coderanger** [comment]
It is just a much older version, you can't get python 3, etc. That is still supported via the `:system` provider though, you can set `default['poise-python']['provider'] = 'system'` in a wrapper cookbook (or role, or whatever) to globally set which provider you want to use.
