### ISSUE TITLE
python_virtualenv attribute consistency

### ISSUE THREAD

**Issue by boxidau** [poise/poise-python#22]
Hi there,

I'm attempting to use poise-python to replace the old python cookbook, so far not too bad but I'm running into issues in an upstream cookbook which uses the `user` variable on the python_virtualenv resource.

Since poise-python uses `owner` instead, this is causing issues which I don't know how to monkey patch.

Any ideas how this could be resolved?

**Comment by coderanger** [comment]
There is no planned direct compat between the two, but if you want to monkey patch it try something like this:

```ruby
class PoisePython::Resources::PythonVirtualenv::Resource
  alias_method :owner, :user
end
```

I'll probably roll something like that into the old python cookbook when I get a chance to build the compat wrapper version.
