### ISSUE TITLE
poise_shell_out is only available from poise 2.5.0

### ISSUE THREAD

**Issue by jujugrrr** [poise/poise-python#34]
`poise-python` 1.2.1 requires `poise_shell_out` which has been added to `poise` 2.5.0.
However the dependencies on poise-pyton are `~> 2.0` https://supermarket.chef.io/cookbooks/poise-python#dependencies. not `~> 2.5`

I've upgraded `poise-python` but got an error because `poise_shell_out` was not there.

https://github.com/poise/poise-python/blob/v1.2.1/lib/poise_python/resources/python_runtime_pip.rb#L119

**Comment by coderanger** [comment]
Thanks for the reminder! I forgot I hadn't already forced it with poise-languages 1.3 :)

**Comment by jujugrrr** [comment]
No worries, thanks for the fix :+1:
