### ISSUE TITLE
Please document how to restructure the repo to be a cookbook so we can fork and test changes

### ISSUE THREAD

**Issue by eric-tucker** [poise/poise-python#38]

**Comment by coderanger** [comment]
Documented over in the Halite README https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook

**Comment by coderanger** [comment]
Though it is worth noting that master on most of my cookbooks is broken this week while I rebuild and simplify my test harness. Also if you want to just fork and run the tests, normal kitchen commands and `rake spec` should be enough.
