### ISSUE TITLE
Cookbook can't be trivially copied with git

### ISSUE THREAD

**Issue by mfischer-zd** [poise/poise-python#41]
We use git submodules extensively as a basis for building machine images using chef-zero.  This is one of the first cookbooks I've seen that makes it impossible to git-clone it into a cookbooks directory from which we can converge a host.

I'm aware that the cookbook is uploaded to Supermarket, but that would entail a number of extra steps as opposed to `git submodule update`.  Another advantage of using Git submodules is that I can pin a specific cookbook ref in my repository.

I appreciate your creativity here, but as a user I'm not feeling the benefits.

**Comment by coderanger** [comment]
Yep, this is source code. You need the compiled output to use with Chef. If you mean overall why do I write things as gems, see the [Halite README](https://github.com/poise/halite#why) or [my blog](https://coderanger.net/how-i-write-cookbooks/).

You can download this as a submodule to a different folder and use Halite to convert it either directly or using the Berkshelf extension.
