### ISSUE TITLE
Wrong python version in virtual env with custom python packages

### ISSUE THREAD

**Issue by scopenco** [poise/poise-python#45]
Hello,

i'm trying to setup virtual env based on IUS packages in CentOS 6.7 x86_64.

I use next recipe for virtual env creation:

```
include_recipe 'yum-ius'

python_runtime '2.7' do
  provider :system
  options :package_name => 'python27'
end

python_virtualenv '/opt/python2_ve' do
  action :create
  python '2.7'
end
```

Converge log:
```
       Recipe: mycookbook::default
         * python_runtime[2.7] action install
           * poise_languages_system[python27] action install
             - install version 2.7.11-1.ius.centos6 of package python27
           - install version 2.7.11-1.ius.centos6 of package python27-devel

       * python_runtime_pip[2.7] action install

       * python_package[setuptools] action install
         - install version 20.2.2 of package setuptools
       * python_package[wheel] action install
         - install version 0.29.0 of package wheel
       * python_package[virtualenv] action install
         - install version 15.0.0 of package virtualenv

       * python_virtualenv[/opt/python2_ve] action create
         - Creating virtualenv at /opt/python2_ve
         * python_runtime_pip[/opt/python2_ve] action install

         * python_package[setuptools] action install
           - install version 20.2.2 of package setuptools
         * python_package[wheel] action install
           - install version 0.29.0 of package wheel
```

After converge i have:
```
[vagrant@ ~]$ /opt/python2_ve/bin/python -V
Python 2.6.6
```

but should be python 2.7.

**Comment by coderanger** [comment]
Please run with `-l debug` to see the underlying commands that are being run. Should help narrow it down a bunch.

**Comment by scopenco** [comment]
i've attached output 

[output.zip](https://github.com/poise/poise-python/files/174752/output.zip)

**Comment by coderanger** [comment]
Ahh right, that makes sense. The package name override isn't considered when computing the path to the python binary so it installing `python27` but then using `/usr/bin/python`. Should be quick fix.

**Comment by scopenco** [comment]
Ok, waiting update on supermarket. 

Thank you.

**Comment by scopenco** [comment]
@coderanger when are you planning to release new version in supermarket?

**Comment by coderanger** [comment]
Probably tomorrow, I usually let changes soak for 24 hours to catch integration bugs with other cookbooks.

**Comment by coderanger** [comment]
You can work around this locally like this:

```ruby
python_virtualenv '/whatever' do
  python '/usr/bin/python27'`
end
```

i.e. give a path to a binary instead of a resource name (it accepts both).

**Comment by coderanger** [comment]
Also you'll need to remove an recreate the venv, it won't detect that the python interpreter has changed in-place.

**Comment by scopenco** [comment]
When will be released new version to supermarket?
