### ISSUE TITLE
Please help to talk with python-beaver community

### ISSUE THREAD

**Issue by nullck** [poise/poise-python#48]
Guys, 

I got this error from poise-python:

```
Requirement already satisfied (use --upgrade to upgrade): boto>=2.8.0 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Requirement already satisfied (use --upgrade to upgrade): conf-d>=0.0.4 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Requirement already satisfied (use --upgrade to upgrade): glob2==0.3 in /usr/local/lib/python2.7/dist-packages (from beaver==31)
Collecting mosquitto>=1.1 (from beaver==31)
STDERR: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement mosquitto>=1.1 (from beaver==31) (from versions: )
No matching distribution found for mosquitto>=1.1 (from beaver==31)
---- End output of ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "beaver==31"] ----
Ran ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "beaver==31"] returned 1
```

Basically is possible to turn around this error by use:

```
pip install git+git://github.com/python-beaver/python-beaver.git@master#egg=beaver
```

But your cookbook needs to use a version instead off a branch, because it I open this ticket at python-beaver github:
https://github.com/python-beaver/python-beaver/issues/401

**Comment by jvheerde-sentia** [comment]
So this will be fixed once a new release of python-beaver has been pushed to pip. I ran into the same problem with poise-python through the beaver cookbook from Chef Supermarket (as I imagine lots of folks did today). It would be nice to be able to tell the Beaver cookbook to use a git repo instead of just a version.

**Comment by nullck** [comment]
In this case your suggestion needs to be apply in poise-python because the cookbook python-beaver use this guy for to install python packages, beaver/recipes/defaults we can see that:

python_package 'beaver' do
  version node['beaver']['version']
  action :install

  if node['beaver']['use_virtualenv']
    virtualenv node['beaver']['virtualenv_path']
  else
    python 'beaver'
  end
end

the directive "python_package" is used by poise-python cookbook, check this for:

cat beaver/metadata.json | grep "poise-python"

"poise-python": ">= 0.0.0",

And the poise-python use pip by to get packages, so to solve our problem we really need that the  python-beaver community to create a new version.

**Comment by coderanger** [comment]
Installing packages from master is problematic because it can't be done idempotently. If you do it via a pip requirements.txt file, it will at least correctly detect when a new version has been installed, but that isn't something I want to put in `python_package`. If you want to run it non-idempotently just put it in an `execute` resource and run it every converge.

**Comment by coderanger** [comment]
Closing this as out of scope.
