### ISSUE TITLE
Can't install with librarian-chef

### ISSUE THREAD

**Issue by eheydrick** [poise/poise-python#5]
Trying to install via librarian-chef results in errors when it tries to resolve dependencies. It looks like it's failing because the cookbook does not contain a metadata file. Is there are reason there's no metadata.rb?

**Comment by coderanger** [comment]
This cookbook is managed via Halite and there is no support for Halite cookbooks in Librarian. You can use Berkshelf (with the Halite extension) as documented in the Halite readme or manually convert the cookbook via `bundle install && rake build`. Or you can use the released version from Supermarket which is already converted for you.
