### ISSUE TITLE
Python 3.3 venv does not support --without-pip

### ISSUE THREAD

**Issue by nmaki** [poise/poise-python#50]
Python 3.3 does have venv but support for --without-pip was not added until 3.4. Currently it seems that it is not going to work to create virtual environments for python 3.3 using this cookbook.

**Comment by coderanger** [comment]
Oy, yeah I'm not sure if I even want to try and untangle that. I guess I can detect the version of venv itself and key off that? This isn't helped by no major OS having 3.3 but not 3.4 so my py3 tests all use 3.4 or 3.2 right now.

**Comment by coderanger** [comment]
This has been added now and is being tested by PyPy3's 3.3 mode.
