### ISSUE TITLE
Default package names for Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by AdamGleave** [poise/poise-python#56]
Hi! 

Thanks for making this package, really useful. It isn't able to autodetect the package name for the newest Ubuntu LTS release, 16.04 (xenial). Adding the following after line 35 of lib/poise_python/python_providers/system.rb does the trick:
'16.04' => %w{python3.5 python2.7},

Best,

Adam

**Comment by coderanger** [comment]
Added in 750eeb1540372d25c9f8690127bc19d2fced4183, thanky.
