### ISSUE TITLE
pip_requirements should support cwd attribute

### ISSUE THREAD

**Issue by dmerrick** [poise/poise-python#59]
For example, I have a requirements.txt with the following:

```
-e .
```

Which in turn pulls up `setup.py` for the list of requirements. When I try to use this `requirements.txt`, I get the following error:

```
STDERR: Directory '.' is not installable. File 'setup.py' not found.
```

Which is because the `pip` command is not being executed from the same directory as the `requirements.txt` file.

**Comment by coderanger** [comment]
Good catch, can you think of a case where running from `File.dirname(requriements_path)` wouldn't be correct? I should check how `pip install -r foo/bar.txt` works, that might be a good case for a manual override.

**Comment by dmerrick** [comment]
I think using `dirname()` would suffice in most situations, but yeah you're right about subdirectories being worth considering.
