### ISSUE TITLE
Python location troubles...

### ISSUE THREAD

**Issue by JCapriotti** [poise/poise-python#6]
I'm using a Centos 6.6 instance provided to me with Python 2.7.6 already installed. I call it by executing `python2.7`. Calling `which python2.7` shows it is in a directory like /opt/somDir/python/bin. The default Python 2.6.6 is also available by calling `python`

When I use the `python_runtime` resource to get the latest version of Python, it appears to install to `/opt/rh/python27/root/usr/bin`. However, calling `python` or `python2.7` still uses the older versions.

I looked at the [documentation for the Software Collections](https://www.softwarecollections.org/en/scls/rhscl/python27/) package that is used, and it says to call `scl enable python27 bash`. After I do that, calling `which python` shows `/opt/rh/python27/root/usr/bin`

I'm curious if the `python_runtime` resource does this by default, or if maybe due to my environment, I need to call it manually?

**Comment by coderanger** [comment]
The cookbook doesn't manipulate your $PATH or otherwise change default lookups. Everything within the code uses absolute paths to specific python binaries so it can be generic across multiple install methods. If you want to make it so running `python` from an interactive shell finds the SCL installation, you could add `source /opt/rh/python27/enable` to your `.bashrc` (or whichever shell you use). If you only interact with Python through the cookbook's tooling, you don't actually need to do this as it will do all the heavy lifting for you internally.

**Comment by JCapriotti** [comment]
Okay, that makes sense; thanks for the explanation. 

I'm setting up my cookbook to do all the Python interaction through there, which seems like the easiest way to go. For example, I can see when I am calling `pip_requirements`, it calls this, which looks like the correct path:

    /opt/rh/python27/root/usr/bin/python -m pip.__main__ install --requirement /opt/applications/myApp/requirements.txt

I don't see any errors in the Chef run but it also doesn't install the requirements. If I call that same command in my shell, it returns this:

    /opt/rh/python27/root/usr/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

If I enable the SCL source in the shell, it works.

So this again seems like a problem with my environment or my usage of the cookbook... but I'm just a little baffled at the moment :). I might get a clean VM going to see what happens...

**Comment by coderanger** [comment]
When `pip_requirements` runs the command, it sets the required environment variables for you that SCL normally sets. If you turn up the log level to `debug` you should be able to see the pip output from the install command.

**Comment by JCapriotti** [comment]
Yeah... I had that set already. It calls `pip --requirement` and the next line is for the next part of the recipe.

    [2015-09-04T07:50:24-05:00] DEBUG: [pip_requirements[/opt/applications/myApp/requirements.txt]] Running python command: /opt/rh/python27/root/usr/bin/python -m pip.__main__ install --requirement /opt/applications/myApp/requirements.txt
    [2015-09-04T07:50:25-05:00] INFO: Processing python_execute[/opt/applications/myApp/manage.py collectstatic --noinput] action run (my_app::default line 57)

**Comment by JCapriotti** [comment]
Well I was missing the `virtualenv` attribute in my `pip_requirement` call. Sorry I was a few knuckles deep in trying to figure out my issue(s) and missed that :/

**Comment by coderanger** [comment]
So if you are using the `python_virtualenv` resource that should be automatic, but if you are using an already existing venv then you would need it.

**Comment by koertkuipers** [comment]
mhhh i find this scl stuff rather unpleasant. i am trying to port some cookbooks from using python to poise-python, but with this scl stuff everything is different between debian and centos. and its not like i can always use the abstractions provided by poise-python. for example i cannot use python_execute in a cron resource, etc.

**Comment by coderanger** [comment]
@koertkuipers Please don't comment on year-old tickets. If you don't want an SCL build, don't use the SCL provider.

**Comment by koertkuipers** [comment]
i was not aware that i can switch provider, i will look into this thanks!

mhhh year old tickets can still be relevant no? should i have created a new
ticket instead? or you prefer me to be silent?

**Comment by coderanger** [comment]
@koertkuipers This is a tracker for bug reports mostly, if you have support questions you can find me on IRC, Discourse, or Slack.

**Comment by koertkuipers** [comment]
ah ok got it
