### ISSUE TITLE
python_package via PIP_HACK_SCRIPT always contacts pypi.python.org

### ISSUE THREAD

**Issue by tokenrain** [poise/poise-python#61]
We have migrated from the deprecated python to poise-python cookbook and have seen a significant slowdown in our Chef runs especially on nodes that use the python_package resource liberally.

We have an internal pypi mirror and an /etc/pip.conf that I have pasted below.

Using pip from the command line we have confirmed that we do not attempt to contact pypi.python.org for install and lists.

I have done some tracing and see that every time we call the python_package resource it then runs the PIP_HACK_SCRIPT which fires up the python interpreter and use the python pip module to do some "things" Even though index_urls array is set correctly in finder_options it seems, for some unknown reason, to issue HTTP GETS against pypi.python.org.

Depending on the time of day and what is happening with the pypi mirrors we get really variable and sometimes lengthy/failing Chef run - really not what we want.

Does anyone have any ideas how to prevent the PIP_HACK_SCRIPT from reaching out to interwebs? 

        def pip_outdated(requirements)
          pip_command(nil, :list, requirements, input: PIP_HACK_SCRIPT, pip_runner: %w{-})
        end

[global]
index-url = http://pypi.local/simple/
extra-index-url = http://pypi.local:8085/simple/
trusted-host = pypi.local
cert = /etc/pki/site/ssl/cacerts/cacert.pem
disable-pip-version-check = on

**Comment by coderanger** [comment]
When you say `index_urls` is correct, you mean you've added a debug print there or something to verify it?

**Comment by coderanger** [comment]
Yeah, I just did a quick repro and the value of `index_urls` is `['http://pypi.local/simple/', 'http://pypi.local:8085/simple/']`. Ping @dstufft maybe?

**Comment by dstufft** [comment]
Um, I'm going to need more context here I think, what is ``PIP_HACK_SCRIPT``.

**Comment by coderanger** [comment]
A terrible thing you helped me write a while ago https://github.com/poise/poise-python/blob/master/lib/poise_python/resources/python_package.rb#L35-L77

**Comment by coderanger** [comment]
Basically a dry-run mode for pip install.

**Comment by dstufft** [comment]
Oh right. Maybe we should just add ``--json`` to ``pip list``.

**Comment by coderanger** [comment]
That part got added with the formatter changes (though I'm still using the old format because parsing isn't too hard). What I need is to know which versions would be installed given an input (possibly with a version constraint). The hack script works most of the time but I'm guessing there is something I'm not passing the right index URLs to :)

**Comment by dstufft** [comment]
@tokenrain Do you have any information about the requests it's making? URLs or anything?

**Comment by dstufft** [comment]
Nothing is immediately obvious looking at ``PIP_HACK_SCRIPT``, more information about what requests are being made might help.

**Comment by tokenrain** [comment]
So I created a foo.py which is the hack script and run at the command line

cat foo.py |/usr/bin/python2.7 -d - zope.interface==4.2.0 

I hacked the hack script to print out the index urls and they are the ones that only point to the local repo

  if options.no_index:
    index_urls = []
  else:
    index_urls = [options.index_url] + options.extra_index_urls
  sys.stderr.write(" ".join(index_urls))

I then edited /etc/hosts and pointed python.pypi.org at a local web server and I get two requests to the fake pythin.org server for every python_package resource run

10.123.14.20 - - [30/Jun/2016:18:35:23 +0000] "GET /simple/zope-interface/ HTTP/1.1" 403 289 "-" "pip/8.1.2 {\"cpu\":\"x86_64\",\"distro\":{\"id\":\"trusty\",\"libc\":{\"lib\":\"glibc\",\"version\":\"2.4\"},\"name\":\"Ubuntu\",\"version\":\"14.04\"},\"implementation\":{\"name\":\"CPython\",\"version\":\"2.7.6\"},\"installer\":{\"name\":\"pip\",\"version\":\"8.1.2\"},\"openssl_version\":\"OpenSSL 1.0.1f 6 Jan 2014\",\"python\":\"2.7.6\",\"system\":{\"name\":\"Linux\",\"release\":\"3.13.0-51-generic\"}}"

10.123.14.20 - - [30/Jun/2016:18:35:23 +0000] "GET /simple/zope-interface/ HTTP/1.1" 403 289 "-" "pip/8.1.2 {\"cpu\":\"x86_64\",\"distro\":{\"id\":\"trusty\",\"libc\":{\"lib\":\"glibc\",\"version\":\"2.4\"},\"name\":\"Ubuntu\",\"version\":\"14.04\"},\"implementation\":{\"name\":\"CPython\",\"version\":\"2.7.6\"},\"installer\":{\"name\":\"pip\",\"version\":\"8.1.2\"},\"openssl_version\":\"OpenSSL 1.0.1f 6 Jan 2014\",\"python\":\"2.7.6\",\"system\":{\"name\":\"Linux\",\"release\":\"3.13.0-51-generic\"}}"

I have dug a little deeper and turned on the debug output to /usr/local/lib/python2.7/dist-packages/pip/index.py and see that it is indeed reaching out to pypi.python.org - I just can not figure out why.

All and any help would be greatly apprciated

apt-xapian-index (0.45)
cffi (1.7.0)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
configobj (4.7.2)
cryptography (1.4)
enum34 (1.1.6)
idna (2.1)
iotop (0.6)
ipaddress (1.0.16)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
ndg-httpsclient (0.4.1)
oauth (1.0.1)
PAM (0.4.2)
pip (8.1.2)
prettytable (0.7.2)
pssh (2.2.2)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.3)
pyOpenSSL (16.0.0)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-dateutil (2.5.3)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2016.4)
PyYAML (3.11)
requests (2.10.0)
setuptools (23.0.0)
six (1.10.0)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.16)
virtualenv (15.0.2)
wheel (0.29.0)
zope.interface (4.2.0)

**Comment by coderanger** [comment]
The fact that it's only for that package seems important, maybe something from find_links?

**Comment by dstufft** [comment]
What about ``process_dependency_links``.

**Comment by tokenrain** [comment]
If it helps at all when I run cat foo.py |/usr/bin/python2.7 -d - zope.interface==4.2.0 there are 4 requests that get to my web server - 2 to the local python mirror and 2 the one masking a python.org

It is 4 of this request

10.123.14.20 - - [30/Jun/2016:22:01:48 +0000] "GET /simple/zope-interface/ HTTP/1.1" 403 289 "-" "pip/8.1.2 {\"cpu\":\"x86_64\",\"distro\":{\"id\":\"trusty\",\"libc\":{\"lib\":\"glibc\",\"version\":\"2.4\"},\"name\":\"Ubuntu\",\"version\":\"14.04\"},\"implementation\":{\"name\":\"CPython\",\"version\":\"2.7.6\"},\"installer\":{\"name\":\"pip\",\"version\":\"8.1.2\"},\"openssl_version\":\"OpenSSL 1.0.1f 6 Jan 2014\",\"python\":\"2.7.6\",\"system\":{\"name\":\"Linux\",\"release\":\"3.13.0-51-generic\"}}"

**Comment by coderanger** [comment]
@dstufft At least for my repro setup, that option is False.

**Comment by coderanger** [comment]
and `find_links` is `[]`.

**Comment by dstufft** [comment]
@coderanger you can repro this locally?

**Comment by coderanger** [comment]
Not fully, I've just been instrumenting the script to see what values it has when a global pip config is present.

**Comment by tokenrain** [comment]
I am not a "Python" guy so please take this debugging trick for what it worth

I rm /usr/local/lib/python2.7/dist-packages/pip/index.pyc and edited /usr/local/lib/python2.7/dist-packages/pip/index.py with the below. Then I ran the hack script and see where python.pypi.org is being called but again can not seem to figure out the code path

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

**Comment by dstufft** [comment]
@tokenrain In the ``PIP_HACK_SCRIPT`` what is the value of options.process_dependency_links?

**Comment by tokenrain** [comment]
False

**Comment by tokenrain** [comment]
I finally tracked this down and of course the issue of always reaching out to pypi.python.org is a case of "stupid user error"

We have a internal pypi repo that is hosted by pypiserver (not pypi-server). We enable this repo via --extra-index-uril config. This means that every request for a package will first g  to our internal pypi mirror and then to our internal pypi repo. This problem was our internal repo (hosted by pypiserver) was issuing 302s to pypi.python.org when it could not find a non internal package. This behavior was easy to disable by passing --disable-fallback to the pypiserver internal repo. 

We no longer see any requests to pypi.python.org. Everything is hosted internally which is what we want.

Sorry for taking your time looking at this aspect of my issue.

The only thing that I discovered that may be considered a bit sub-optimal is the number of HTTP calls that the python_package resource calls via the PIP_HACK_SCRIPT.

The PIP_HACK_SCRIPT creates 2 HTTP GET requests for every package for every url that you have in your pip.conf. The lines below from the PIP_HACK_SCRIPT are the ones that are making the calls. This means for us every call to python_package  results in launching the python interpreter  and making 4 HTTP requests. When we have nodes that have lots of python_package resources this can increase converge times significantly.

I was wondering if there was a simple modification that could be made to the PIP_HACK_SCRIPT that such that only a single HTTP request is required to obtain the needed info?

All and any help is much appreciated

# PIP_HACK_SCRIPT lines that lead to HTTP requests
found = finder.find_requirement(req, True)
all_candidates = find_all(req.name)

**Comment by coderanger** [comment]
@tokenrain That would be up to the pip team, though the compat requirements of PyPI have made it difficult to optimize over the years. Maybe when Warehouse saves us all (<3 @dstufft).

**Comment by dstufft** [comment]
It's actually better for us to have smaller, easier to cache requests rather than larger harder to cache requests. I think we're down to 1 HTTP request to discover a list of versions per package, and 1 HTTP request to actually download the selected file. I don't think we can reduce the number of HTTP requests without combining things so that a single request can fetch information for more than one package at a time. 

The problem then is there's no clear set of criteria for how you'd combine multiple packages into a single request/response? The only real way to do that is to let pip dynamically pass in a list of packages. The problem then becomes that for each unique set of packages that's a unique set of request/responses to cache which makes it harder to effectively leverage our CDN to scale PyPI. By making 1 HTTP request per package, we make it easier to almost always serve items out of the cache because it doesn't matter what set of packages someone is installing, a request for information about the ``foo`` package is always the same. It's also what makes static mirrors possible since there's no intelligence on the server side that it needs to respond to.
