### ISSUE TITLE
python_runtime does not install the latest pip version. 

### ISSUE THREAD

**Issue by J-cztery** [poise/poise-python#62]
python_runtime 'python2.7' do
  version '2.7'
  pip_version true
end

Does not result in the latest pip being installed. The problem seems to be install_pip method...

My environment is : Windows 2012 R2 Core, Python 2.7.10 (pip 7.0.1 comes with it?)
I do not understand the code and what should be the version of the new_resource but the condition below makes chef think that correct version of pip is installed as long as a version of pip is installed and the latest is requested. 
files/halite_gem/poise_python/resources/python_runtime_pip.rb: 
def install_pip
if new_resource.version
            # Already up to date, we're done here.
            return if current_resource.version == new_resource.version
          else
            # We don't wany a specific version, so just make a general check.
             return if current_resource.version <-- this condition is incorrect when new_resource.version is not set 
end

**Comment by coderanger** [comment]
It mirrors the core `package` resource behavior of not upgrading in-place unless requested. That means if pip is already installed and you request "latest" it doesn't upgrade at all. `true` is basically like putting `>= 0` as a version constraint. I've debated adding something like `:upgrade` to really always ride latest, but you can do that yourself via `python_package 'pip' do action :upgrade end` so I've not put in in explicitly.

**Comment by J-cztery** [comment]
@coderanger  what you are saying seems reasonable but comments in the code are saying something completely opposite. Comments mention the fact that it always installs the latest and then possibly downgrades... 
And from the documentation i can infer that by default i will end up with the latest version of pip. This is clearly not the case.

**Comment by coderanger** [comment]
It's the same definition of "latest" as `package 'whatever' do action :install end` gets you. You get the latest version at the point that it is installed, but if already installed then it does nothing. The behavior for "always latest" corresponds to `action :upgrade`.

**Comment by J-cztery** [comment]
"pip_version – Version of pip to install. If set to true, use the latest. If set to false, do not install pip. Can also be set to a URL to a copy of the get-pip.py script. (default: true)"

This is what documentation says. It would be fine if it did what you said: "You get the latest version at the point that it is installed", so when it installs python (which installs pip 7.1.x), it should go and grab the latest version (8.x.x) of pip and install it. I would not complain if after that time version 9.x went out and it did not install it. But that is not the problem here. 

The problem here is that on a pristine installation, the recipe installs python and does not fulfill the promise of installing the latest pip. And this is what my bug report is about.

**Comment by coderanger** [comment]
Again, "install" means something more specific within the Chef lexicon as compared to normal usage. Your install is _not_ pristine if pip is already installed (except with recent Python 3.4 which bundles pip). The only way you get the behavior you describe is if you are installing pip outside of this cookbook somehow, probably via an OS package :)

**Comment by J-cztery** [comment]
Well, if you are happy with the behaviour and do not accept my feedback, feel free to close the issue. But keeping current behaviour does not solve anyone's problems. I wasted a few days having strange issues which eventually boiled down to pip being old, which tuned out to be the problem with this recipe. I do not recommend. 
Thank you for your time.

**Comment by coderanger** [comment]
The behavior is correct, it sounds like the docs are what needs to be changed.

**Comment by J-cztery** [comment]
@coderanger, your work around of python_package 'pip' do action :upgrade end does the trick. Thanks!
