### ISSUE TITLE
python_package - please give example how to pass install option to specify where binaries are installed

### ISSUE THREAD

**Issue by eric-tucker** [poise/poise-python#63]
Amazon Linux

I want to run pip with the install option of --install-scripts=/usr/bin

I tried the following:

```
  python_package "pip" do
    action :upgrade
    user "root"
    group "root"
    install_options "--install-scripts=/usr/bin"
  end
```

```
  python_package "pip" do
    action :upgrade
    user "root"
    group "root"
    install_options "--install-option='--install-scripts=/usr/bin'"
  end
```

Neither work, though the second did not error out but did NOT install the binary to /usr/bin/pip

**Comment by coderanger** [comment]
`pip` is not installed in a way you can control, nor should you ever use the actual `pip` binary like that. Always use `python -m pip` in scripts and automation.
