### ISSUE TITLE
python – Name of the python_runtime resource to use. If not specified, the most recently declared

### ISSUE THREAD

**Issue by pecigonzalo** [poise/poise-python#64]
I would suggest we revert this to using system if no venv declared, this i a really nasty default as you have to trace which was the last venv declaration to know where its installing or change all python_package declaration to use something like `python '2'`.

**Comment by coderanger** [comment]
This is part of the Poise core behaviors. It can bite you if you aren't careful but is built to allow flexibility with reusable cookbooks. If you don't specify an interpreter, you are literally saying "I don't care what Python you give me" which is not what you meant in this case.

**Comment by coderanger** [comment]
As an example of the flexibility bit, you could use `python_runtime` to install from PyPy or Python 3, and because it was the last declared parent resource it will be used automatically by all further resources even in cookbooks you didn't write :)

**Comment by pecigonzalo** [comment]
I understand is part of the core behaviour, but it is IMHO a bad decision, as i could be getting the venv of another cookbook i did not declare.
Normal behavior is "if you dont specify you use system default" which correct, "i dont care what version it is". But using the last declared venv is not preferred in any i case i believe, it could lead to unexpected behavior and conflicts with the simplicity of a CM DSL.

**Comment by pecigonzalo** [comment]
As an alternative, the cookbook could provide an attribute to use as default. Something we could declare as an environment or role default.

**Comment by coderanger** [comment]
venvs are probably worth special-casing to not register themselves as default-able parents. I already did that for venvs created within an `application` resource which is what I would recommend for per-app venvs. It's a bit fuzzier for if there should be a "global" venv concept or not. Unfortunately there have been multiple tools which pitch that as a "best practice" so some communities expect it and others don't.

**Comment by coderanger** [comment]
Really though, be explicit and allow the dependency inejction framework to do its job :)

**Comment by coderanger** [comment]
If you want to fix this locally you can make a trivial subclass of the venv resource in your own cookbook:

```ruby
require 'poise_python/resources/python_virtualenv'

class MyVirtualenv < PoisePython::Resources::PythonVirtualenv::Resource
  provides(:my_virtualenv)
  container_default(false)
  subclass_providers!
end
```

If you throw that in a `libraries/my_virtualenv.rb` file and then use `my_virtualenv` instead of `python_virtualenv` it will create venvs that aren't default parents :)

**Comment by pecigonzalo** [comment]
Yes, but this is beyond the scope of my own cookbook, this could affect any cookbook that depends on your cookbook and there are a few.

**Comment by coderanger** [comment]
As I said, that is intentional.

**Comment by pecigonzalo** [comment]
Yeah, i got that, but that is not a sane default.

**Comment by coderanger** [comment]
Do you have an example of it being a problem in correctly written code?

**Comment by coderanger** [comment]
(the whole point this cookbook was written for was to allow using non-standard python interpreters like PyPy with Chef without having to fork every cookbook ever)

**Comment by pecigonzalo** [comment]
Any recipe doing
```
python_package 'somepackage'
```
executed after any recipe that creates a virtualenv.

would trip on this. Yeah i can pin it to a a python run-time, but as you said, i might no care, i just want system default, but system wide accessible. Not pinned inside a venv.

If you check most resources in the supermaker, and Chef's own resources, they have standard defaults, and doing something like `package 'somepackage'` is correctly written code.

**Comment by coderanger** [comment]
So that part is fine, it's creating the venv that I think you need to change. Anywhere that wants to create an app-specific virtualenv should use the `application_virtualenv` resource (or use normal `virtualenv` in the context of an `application` resource which is the same thing). That will create the venv without marking it as a potential default parent.

**Comment by pecigonzalo** [comment]
Sorry i dont think i fully understood your last comment, could you put an example?

**Comment by coderanger** [comment]
```ruby
python '2.7' do
  provider :system
end

python_package 'foo' # uses /usr/bin/python2.7

application_virtualenv '/bar'

python_package 'bar' # uses /usr/bin/python2.7

virtualenv '/baz'

python_package 'baz' # uses /baz/bin/python2.7
```

Similarly if you're deploying an "application" written in Python you can use the `application_python` stuffs to get nicer things:

```ruby
application '/whatever'
  python '2.7'
  virtualenv
  python_package 'foo' # uses /whatever/.env/bin/python2.7
end

python_package 'bar' # uses /usr/bin/python2.7
```

The `virtualenv` call inside `application` is non-global but sets application-level state so things later in the block will use it without affecting anything outside the block. One of those two things is probably what you want.

**Comment by pecigonzalo** [comment]
I would still think poise-python should no use the last default in all honesty, but those 2 options/cookbooks certainly mitigate it as they provide an alternative.

Cheers, and thanks for the help

**Comment by coderanger** [comment]
The point of the default's applying even to top-level stuffs is you could take a reusable cookbook for, say, supervisord and deploy it inside a venv without having to touch anything.
