### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by bdwyertech** [poise/poise-python#65]
Something like this is no-bueno

```
python_runtime 'myapp' do
  version '3'
end

python_virtualenv 'myapp' do
  path '/var/www/myapp/venv'
  python 'myapp'
  user 'vagrant'
  group 'vagrant'
end

pip_requirements 'myapp' do
  path '/var/www/myapp/requirements.txt'
  virtualenv 'myapp'
  user 'vagrant'
  group 'vagrant'
end
```

Borks on the `python_virtualenv`.  Some stuff in there ends up getting owned by root.  My guess is some part of the `python_virtualenv` resource calls a `shell_out` to `pip` without all the environment variables set somewhere.  I usually explicitly set `USER` and `HOME`.  Seen the issue with execute resources in the past.

**Comment by coderanger** [comment]
Dup of #42?

**Comment by bdwyertech** [comment]
Yup, looks like it.  Odd, I searched open issues for permissions and didn't see that one...  I'll close this out out. @coderanger
