### ISSUE TITLE
python_runtime does not match anything.

### ISSUE THREAD

**Issue by edupo** [poise/poise-python#82]
Trying to install python here, my recipe looks like:

    python_runtime '3' # I'm not demanding so install what you consider...

So let's try to converge on an Ubuntu 16.04

    ...
    PoiseLanguages::Error: Package python3.5-dev would install , which does not match 3. 
    Please set the package_name or package_version provider options.

Ok, maybe I need to be more specific apparently (but I supposed defaults were right!)

    python_runtime '3' do
      options :system, package_name: 'python3.5-dev'
    end

Converging...

    ...
    PoiseLanguages::Error: Package python3.5-dev would install , which does not match 3.
    Please set the package_name or package_version provider options.

Oh! Come on! Is not matching yet? Ok, let's see...

    python_runtime 'python3.5-dev' do
      options :system, package_name: 'python3.5-dev'
    end

This will work...

    ...
    PoiseLanguages::Error: Package python3.5-dev would install , which does not match python3.5-dev. 
    Please set the package_name or package_version provider options.

What?!

**Sorry, I can't see what I'm doing wrong (something terrible apparently). Any help?**

Chef version:

    kitchen@df2f58a5a522:~$ chef-client --version
    Chef: 12.17.44

Berlsfile.lock:

    DEPENDENCIES
      dev_python
        path: .
        metadata: true
      poise-python (~> 1.5.1)
    GRAPH
      dev_python (0.3.0)
        poise-python (~> 1.5.1)
      poise (2.7.1)
      poise-archive (1.3.0)
        poise (~> 2.6)
      poise-languages (2.0.4)
        poise (~> 2.5)
        poise-archive (~> 1.0)
      poise-python (1.5.1)
        poise (~> 2.7)
        poise-languages (~> 2.0)

**Comment by coderanger** [comment]
This is an unfortunately unhelpful error message because `nil.to_s == ''` (there is a pending fix in master to make it show an actual `nil`) so what it's trying to say is it can't find a candidate version for `python3.5-dev`. What OS are you on and do you have any customizations to your package servers et al?

**Comment by edupo** [comment]
Host OS:

    Linux edu-VirtualBox 4.4.0-51-generic #72~14.04.1-Ubuntu SMP Thu Nov 24 19:22:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm using a Docker image of Ubuntu 16.04 with all defaults on packaging systems.

But I login into the machine and successfully installed that package `python3.5-dev`

```
kitchen@df2f58a5a522:~$ sudo apt install python3.5-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-dev-bin libc6-dev libexpat1-dev libpython3.5 libpython3.5-dev linux-libc-dev manpages manpages-dev
Suggested packages:
  glibc-doc man-browser
The following NEW packages will be installed:
  libc-dev-bin libc6-dev libexpat1-dev libpython3.5 libpython3.5-dev linux-libc-dev manpages manpages-dev
  python3.5-dev
0 upgraded, 9 newly installed, 0 to remove and 6 not upgraded.
Need to get 45.3 MB of archives.
After this operation, 82.8 MB of additional disk space will be used.
Do you want to continue? [Y/n]
...
Lots of installing stuff
...
kitchen@df2f58a5a522:~$ python3 --version
Python 3.5.2
```

**Comment by coderanger** [comment]
Are you running an apt update before the Python runtime resource?

**Comment by edupo** [comment]
Yes

**Comment by edupo** [comment]
Found in my docker file:

    RUN rm -rf /var/lib/apt/lists/*

The converge continues with other errors (our own ones).

Thank you!
