### ISSUE TITLE
python_package `pyopenssl` does not actually install the package

### ISSUE THREAD

**Issue by jrlonan** [poise/poise-python#83]
## Code
Chef recipe
```
include_recipe 'poise-python'

python_package 'pyopenssl' do
  action :install
end
```

## Expected Behaviour
`pyopenssl` package is installed and is shown when `pip list` is run

## Actual behaviour
When  I run Kitchen tests, the Chef logs shows that the resource is installed
```
         * python_package[pyOpenSSL] action install
           - install version 16.2.0 of package pyOpenSSL
```

However, my serverspec tests failed
```
       Command "pip list | grep -i pyOpenSSL"
         exit_status
           should eq 0 (FAILED - 1)

       Failures:
       
         1) Command "pip list | grep -i pyOpenSSL" exit_status should eq 0
            Failure/Error: its(:exit_status) { should eq 0 }
              
              expected: 0
                   got: 1
              
              (compared using ==)
              /bin/sh -c pip\ list\ \|\ grep\ -i\ pyOpenSSL
```

And I confirmed this when logging in to the test server and manually checked in the command line, pyopenssl does not exist:
```
[root@x.x.x.x centos]# pip list | grep -i pyopenssl
[root@x.x.x.x centos]#
```
I tried adding the version in the Chef resource or changing the package name to `PyOpenSSL`, but it doesn't resolve the issue.

**Comment by coderanger** [comment]
On CentOS it defaults to using the SCL (Software Collections) packages for Python. This gives you much newer versions of Python but unfortunately means that things can be confusing. `/usr/bin/python` and `/usr/bin/pip` are both from the system package, which is probably an older version (specifics depend on if this is CentOS 6 or 7). If you run the command `scl enable python27 'python -m pip list` you'll likely see the expected output.

If you want to force it to use the system package version of Python instead, there are instructions in the README.

**Comment by jrlonan** [comment]
Thank you for the tip! I don't need to use the system package so your command works for my serverspec test.

Thanks again!

**Comment by coderanger** [comment]
This is great example of why you shouldn't be writing tests like that, they are super-fragile and not how Chef tests should work :-) Check out https://coderanger.net/overtesting/ for more info, but going to close this out as it sounds like you're unblocked.
