### ISSUE TITLE
Unable to control/pin patch version of Python runtime

### ISSUE THREAD

**Issue by azhang4351** [poise/poise-python#84]
Wanted to keep python runtime version at something like 2.7.10, but appears that the cookbook only handles version pinning up to the minor version (ie 2.7). As a result this will always pull the latest version of 2.7.x

Would like the capability for the cookbook resource to pin to a specific patch version, not just minor version

**Comment by coderanger** [comment]
It uses a string prefix match so anything that is a string will work with it. More likely you are using a provider that doesn't offer 2.7.10.
