### ISSUE TITLE
ChefSpec matchers for LWRP

### ISSUE THREAD

**Issue by sean-kang** [poise/poise-python#89]
I am working on upgrading wrapper cookbooks that used outdated python cookbook but I cannot find ChefSpec matcher for python_package LWRP.

The previous cookbook had ChefSpec matchers for LWRP. For example, it provided install_python_pip for python_pip LWRP. The matchers were defined in the following code.
https://github.com/poise/python/blob/master/libraries/matchers.rb

Is poise-python cookbook lacking the same type of matchers or am I missing something?

**Comment by coderanger** [comment]
::magic:: ✨ 

It's handled deep inside my Poise helper library, it automatically creates matchers for all actions as well as the rarely used runner accessors.

**Comment by sean-kang** [comment]
It will be really nice if the magical matchers are documented somewhere.

**Comment by coderanger** [comment]
Not sure what there is to document other than "matchers exist"? They all follow the entirely standardized format, and really ChefSpec shouldn't have required them to be defined like that in the first place but it's tricky to avoid it.

**Comment by waltercool** [comment]
I found this just doing monkey testing, but you can do \<action\>_\<resource\>(\<parameter\>) and works fine.

For example, install_python_package('whatever')

**Comment by coderanger** [comment]
Yes, that is the pattern all matchers always use :-)
