### ISSUE TITLE
Package fails to install when options are specified

### ISSUE THREAD

**Issue by redi-russela** [poise/poise-python#9]
Whenever I add an `options` property to my `python_package` resource, it fails. For example, my resource looks similar to:

    python_package 'tinydb' do
      version '2.4'
      virtualenv my_venv_dir
      options '--extra-index-url http://www.example.com/api/pypi/my-repo/simple'
    end

Even a `'-v'` option fails.

    [2015-10-07T14:55:54-04:00] DEBUG: [python_package[tinydb]] Running python command: /opt/my-venv/bin/python #- list -v --outdated tinydb\=\=2.4
    
    Usage:
      pip <command> [options]
    
    Commands:
      install                     Install packages.
	...<snip>...
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated:
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated: Usage:
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated:   pip <command> [options]
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated:
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated: Commands:
    [2015-10-07T14:55:55-04:00] DEBUG: [python_package[tinydb]] Unparsable line in pip outdated:   install                     Install packages.
	...<snip>...
    
        * No candidate version available for tinydb
        ================================================================================
        Error executing action `install` on resource 'python_package[tinydb]'
        ================================================================================
    
        Chef::Exceptions::Package
        -------------------------
        No candidate version available for tinydb
    
        Resource Declaration:
        ---------------------
        # In /home/me/chef-repo/cookbooks/my-cookbook/recipes/default.rb
    
         34: python_package 'tinydb' do
         35:   version '2.4'
         36:   virtualenv my_venv_dir
         37:   options '-v'
         38: end
         39:
    
        Compiled Resource:
        ------------------
        # Declared in /home/me/chef-repo/cookbooks/my-cookbook/recipes/default.rb:34:in `from_file'
    
        python_package("tinydb") do
          action :install
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          options "-v"
          package_name "tinydb"
          version "2.4"
          timeout 900
          declared_type :python_package
          cookbook_name :"my-cookbook"
          recipe_name "default"
          parent_python python_virtualenv[/opt/my-venv]
        end
    
    [2015-10-07T14:55:55-04:00] INFO: Running queued delayed notifications before re-raising exception
    [2015-10-07T14:55:55-04:00] DEBUG: Re-raising exception: Chef::Exceptions::Package - python_package[tinydb] (my-cookbook::default line 34) had an error: Chef::Exceptions::Package: No candidate version available for tinydb
    /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
      /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
      /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
      /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:144:in `process_resource_requirements'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:120:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
      /opt/chefdk/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
      /opt/chefdk/bin/chef-solo:51:in `load'
      /opt/chefdk/bin/chef-solo:51:in `<main>'
    
    Running handlers:
    [2015-10-07T14:55:55-04:00] ERROR: Running exception handlers
    Running handlers complete
    [2015-10-07T14:55:55-04:00] ERROR: Exception handlers complete
    [2015-10-07T14:55:55-04:00] FATAL: Stacktrace dumped to /home/me/chef-solo/chef-stacktrace.out
    [2015-10-07T14:55:55-04:00] DEBUG: Chef::Exceptions::Package: python_package[tinydb] (my-cookbook::default line 34) had an error: Chef::Exceptions::Package: No candidate version available for tinydb
    /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
    /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
    /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
    /opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
    /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:144:in `process_resource_requirements'
    /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:120:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
    /opt/chefdk/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
    /opt/chefdk/bin/chef-solo:51:in `load'
    /opt/chefdk/bin/chef-solo:51:in `<main>'
    Chef Client failed. 2 resources updated in 23.201344547 seconds
    [2015-10-07T14:55:55-04:00] ERROR: python_package[tinydb] (my-cookbook::default line 34) had an error: Chef::Exceptions::Package: No candidate version available for tinydb
    [2015-10-07T14:55:55-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by coderanger** [comment]
Thanks for the report! Missed a rogue `#` which was commenting out all the CLI arguments when there were options.

**Comment by redi-russela** [comment]
Thanks for the super-quick fix. When do you plan on making your next release?

**Comment by coderanger** [comment]
@redi-russela Probably on Monday or around there.
