### ISSUE TITLE
poise-python depends on Chef ~> 12

### ISSUE THREAD

**Issue by tanner-bruce** [poise/poise-python#90]
With the release of Chef 13 we are now receiving the error `ERROR: Cookbook 'poise-python' version '1.5.2' depends on chef version ["~> 12"], but the running chef version is 13.0.113` on Chef client runs

**Comment by coderanger** [comment]
Yes, it will take me a few days to get all my releases done. Please be patient with Chef major releases, these things take time. The master branch of this cookbook is currently passing tests on Chef 13, but I have 11 other repos failing and I want to make sure there are no cross compat issues.
