### ISSUE TITLE
missing metadata.rb

### ISSUE THREAD

**Issue by bierdybard** [poise/poise-python#92]
Hello,

My org maintains an internal supermarket with strict license restrictions, automated by checking the metadata.rb file. This repo doesn't have metadata.rb so I am not able to pull in the cookbook internally despite your licensing being compatible.

Would you please consider adding metadata.rb and tagging a new release?

Thank you!

**Comment by coderanger** [comment]
See https://github.com/poise/application_python/issues/80

Please don't open a bunch more of these, every one of my cookbooks works like this.

**Comment by bierdybard** [comment]
My apologies on this, this repo isn't having the same issue I reported for application_python.
