### ISSUE TITLE
Make sure the virtualenv module may be used by other users

### ISSUE THREAD

**Issue by rveznaver** [poise/poise-python#94]
Hi,

Not sure if really a bug, but may be good to document.
If the default umask is set at a stricter level, the Python packages that get installed inherit it and get installed with permissions that do not allow users to use them.

Example:
The the os-hardening cookbook sets the root umask to 0027, therefore setting the Python packages installed by this cookbook to 0640 (by inheritance).

Example workaround (for `virtualenv`):
```ruby
python_runtime 'myapp' do
  version '2.7'
  options :system
end

# Make sure the installed virtualenv may be used by the user
file '/usr/local/lib/python2.7/dist-packages/virtualenv.py' do
  mode '0644'
end

python_virtualenv "/opt/myapp/env" do
  python 'myapp'
  user   'myapp'
  group  'myapp'
end
```

**Comment by coderanger** [comment]
I'm not really sure what there is to document other than "whatever umask is set for Chef will apply to all Chef-run commands". You can set the umask either in the Chef config file or directly in recipe code.

**Comment by rveznaver** [comment]
True, the main reasoning of reporting this issue is in case someone else runs into it :)
In addition, it may catch the operator by surprise since Python is installed via the package manager (which makes sure the permissions on Python are correct), and the rest is installed via the pip script (which does not seem to manage permissions).

**Comment by coderanger** [comment]
Yeah, it's mostly that it's not really specific to Python per se. It's a general weakness of umask as a security system :-/ We should probably be better about allowing per-resource umask control like we do with user/group/env but until that goes in core Chef I think it's safe to call it overkill (and maybe ever then, but that would be a starting point).
