### ISSUE TITLE
centos 7: uwsgi install succeeds, but can't be run, manual pip commands can't be run

### ISSUE THREAD

**Issue by daften** [poise/poise-python#97]
I've added a cookbook so it can easily be tested. Just run a vagrant up inside the cookbook and you should be able to produce the following easily:

```
[vagrant@pootle-berkshelf ~]$ sudo su pootle
bash-4.2$ cd ~
bash-4.2$ source /opt/pootle/bin/activate
(pootle)bash-4.2$ uwsgi
uwsgi: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
(pootle)bash-4.2$ pip uninstall uwsgi
Traceback (most recent call last):
  File "/opt/pootle/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/pootle/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/opt/pootle/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/opt/pootle/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

Manual pip commands (directly with pip or with python -m pip) all fail with either this error or an unknown exception error.

Does anybody have any idea why this happens?

[cookbook-pootle.zip](https://github.com/poise/poise-python/files/1231336/cookbook-pootle.zip)

**Comment by coderanger** [comment]
This is because the default install provider on RHEL and CentOS is the SCL packages, which have to be used via the `scl enable` command line tool. Within Chef, the cookbook hides this from you because the install source is modular. If you want to use system packages, you can configure that either in node attributes, via the `python_runtime_options` pseudo-resource, or on the `python_runtime` resource itself.

**Comment by daften** [comment]
Thanks @coderanger for the quick reply. Pip does work again now, still running into a problem with uwsgi, but that's something outside of this cookbook I think.

However, this behaviour, wouldn't it make sense to document this somewhere? E.g. under a known problems section in the readme. Since SCL is the default on centos it seems and a virtualenv is used a lot.

**Comment by coderanger** [comment]
> The scl provider installs Python using the Software Collections packages. This is only available on RHEL, CentOS, and Fedora. SCL offers more recent versions of Python than the system packages for the most part. If an SCL package exists for the requested version, it will be used in preference to the system provider.
