### ISSUE TITLE
Python_runtime resource does not add python in system path in Windows

### ISSUE THREAD

**Issue by TheKatarGit** [poise/poise-python#98]
I was not able to find an clear way for python_runtime resource to add installed python into system path in windows. Is this option still not supported? I'm using Windows Server 2012r2. If it makes sense, I install several python versions, ranging from 2.5 to 2.7, and not a single of them is accessible from cmd.

**Comment by coderanger** [comment]
There is no `python_environment` resource, do you mean `python_runtime` or `python_virtuealenv`?

**Comment by TheKatarGit** [comment]
@coderanger oops, sorry. I mean `python_runtime`

**Comment by coderanger** [comment]
That would be a function of which install provider you used, though windows only offers one so this probably means the MSI installers don't have that option enabled by default. Not a whole lot I can do so just use the `windows_path` resource to set it up.

**Comment by TheKatarGit** [comment]
@coderanger thanks a lot!
